# Generated by Django 2.1.7 on 2019-10-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, unique=True)),
                ('seq', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_time', 'post_id'],
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('product_url', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('goal_num', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('soboon_price', models.IntegerField(default=0)),
                ('shipping_address', models.TextField()),
                ('closing_time', models.DateTimeField()),
                ('finished_time', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.Category')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('pwd', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
                ('legion', models.CharField(max_length=254)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '이용자',
                'verbose_name_plural': '이용자들',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.Post'),
        ),
        migrations.AddField(
            model_name='join',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.User'),
        ),
        migrations.AddField(
            model_name='join',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soboonSer.User'),
        ),
    ]
